import { type NextRequest, NextResponse } from "next/server"
import Tesseract from "tesseract.js"
import { generateText } from "ai"
import { openai } from "@ai-sdk/openai"

export async function POST(request: NextRequest) {
  try {
    const { image, preference, customRestriction } = await request.json()

    if (!image || !preference) {
      return NextResponse.json({ error: "Missing required fields: image and preference" }, { status: 400 })
    }

    console.log("Starting analysis for preference:", preference)

    // Convert base64 to buffer for OCR processing
    const base64Data = image.replace(/^data:image\/[a-z]+;base64,/, "")
    const buffer = Buffer.from(base64Data, "base64")

    console.log("Image buffer created, starting OCR...")

    // Step 1: Extract text from image using Tesseract OCR
    const worker = await Tesseract.createWorker("eng", 1, {
      logger: (m) => {
        if (m.status === "recognizing text") {
          console.log(`OCR Progress: ${Math.round(m.progress * 100)}%`)
        }
      },
    })

    const {
      data: { text },
    } = await worker.recognize(buffer, {
      rectangle: { top: 0, left: 0, width: 0, height: 0 },
    })

    await worker.terminate()
    console.log("OCR completed. Raw text length:", text.length)
    console.log("OCR text preview:", text.substring(0, 300) + "...")

    // Step 2: Parse ingredients from extracted text
    const ingredients = parseIngredients(text)
    console.log("Parsed ingredients:", ingredients)

    if (ingredients.length === 0) {
      console.log("No ingredients found, trying fallback parsing...")
      // Fallback: try to extract any text that might be ingredients
      const fallbackIngredients = text
        .split(/[,;\n]/)
        .map((item) => item.trim())
        .filter((item) => item.length > 2 && item.length < 50)
        .slice(0, 20)

      if (fallbackIngredients.length === 0) {
        return NextResponse.json(
          {
            error:
              "No ingredients could be extracted from the image. Please ensure the ingredient list is clearly visible and try again.",
            extractedText: text.substring(0, 200), // Return some text for debugging
          },
          { status: 400 },
        )
      }

      ingredients.push(...fallbackIngredients)
    }

    // Step 3: AI-powered dietary compliance analysis
    console.log("Starting AI analysis with", ingredients.length, "ingredients...")
    const analysisResult = await analyzeDietaryComplianceWithAI(ingredients, preference, customRestriction)
    console.log("AI analysis completed:", analysisResult.result)

    return NextResponse.json({
      ingredients,
      extractedText: text.substring(0, 500), // Include for debugging
      ...analysisResult,
    })
  } catch (error) {
    console.error("Analysis API error:", error)
    return NextResponse.json(
      {
        error: "Internal server error during analysis. Please try again.",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 },
    )
  }
}

function parseIngredients(text: string): string[] {
  console.log("Parsing ingredients from text...")

  // Clean and normalize the text
  const cleanText = text.replace(/\n/g, " ").replace(/\s+/g, " ").trim()

  // Multiple patterns to find ingredient lists
  const ingredientPatterns = [
    // English patterns
    /ingredients?:?\s*(.+?)(?:\.|nutritional|nutrition|allergen|contains|may contain|net weight|serving|calories|$)/i,
    /ingrédients?:?\s*(.+?)(?:\.|nutritional|nutrition|allergen|contains|may contain|net weight|serving|calories|$)/i,
    // Arabic patterns
    /مكونات:?\s*(.+?)(?:\.|معلومات غذائية|قد يحتوي|الوزن الصافي|$)/i,
    // Spanish patterns
    /ingredientes:?\s*(.+?)(?:\.|información nutricional|puede contener|peso neto|$)/i,
    // Look for lists that start with common ingredients
    /(water|sugar|salt|flour|oil|milk|wheat|corn|rice|soy|egg|butter|cheese|meat|chicken|beef|pork|fish|tomato|onion|garlic|spices|natural flavors|artificial flavors|preservatives|vitamins|minerals|citric acid|sodium|potassium|calcium|iron|vitamin|protein|carbohydrate|fat|fiber|cholesterol|trans fat|saturated fat|unsaturated fat|monounsaturated|polyunsaturated|omega|antioxidant|emulsifier|stabilizer|thickener|coloring|flavoring|sweetener|sugar substitute|high fructose corn syrup|corn syrup|glucose|fructose|sucrose|lactose|maltose|dextrose|sorbitol|mannitol|xylitol|aspartame|sucralose|acesulfame|stevia|monk fruit|erythritol|glycerin|lecithin|carrageenan|guar gum|xanthan gum|agar|pectin|gellan|locust bean|tapioca|modified starch|corn starch|potato starch|wheat starch|rice starch|tapioca starch|modified corn starch|modified potato starch|modified wheat starch|modified rice starch|modified tapioca starch|caramel color|annatto|turmeric|paprika|beta carotene|lycopene|anthocyanin|chlorophyll|cochineal|carmine|red 40|yellow 5|yellow 6|blue 1|blue 2|green 3|titanium dioxide|iron oxide|calcium carbonate|magnesium carbonate|potassium carbonate|sodium carbonate|ammonium carbonate|calcium sulfate|magnesium sulfate|potassium sulfate|sodium sulfate|ammonium sulfate|calcium chloride|magnesium chloride|potassium chloride|sodium chloride|ammonium chloride|calcium phosphate|magnesium phosphate|potassium phosphate|sodium phosphate|ammonium phosphate|calcium citrate|magnesium citrate|potassium citrate|sodium citrate|ammonium citrate|calcium lactate|magnesium lactate|potassium lactate|sodium lactate|ammonium lactate|calcium acetate|magnesium acetate|potassium acetate|sodium acetate|ammonium acetate|calcium propionate|magnesium propionate|potassium propionate|sodium propionate|ammonium propionate|calcium benzoate|magnesium benzoate|potassium benzoate|sodium benzoate|ammonium benzoate|calcium sorbate|magnesium sorbate|potassium sorbate|sodium sorbate|ammonium sorbate|bht|bha|tbhq|tocopherol|ascorbic acid|ascorbyl palmitate|sodium erythorbate|sodium bisulfite|sodium metabisulfite|potassium bisulfite|potassium metabisulfite|sulfur dioxide|nitrite|nitrate|monosodium glutamate|msg|disodium inosinate|disodium guanylate|yeast extract|autolyzed yeast|hydrolyzed protein|hydrolyzed soy protein|hydrolyzed wheat protein|hydrolyzed corn protein|hydrolyzed rice protein|hydrolyzed pea protein|hydrolyzed vegetable protein|soy protein isolate|whey protein isolate|casein|sodium caseinate|calcium caseinate|potassium caseinate|magnesium caseinate|milk protein|egg protein|wheat protein|corn protein|rice protein|pea protein|hemp protein|quinoa protein|chia protein|flax protein|sunflower protein|pumpkin protein|sesame protein|almond protein|cashew protein|walnut protein|pecan protein|hazelnut protein|brazil nut protein|macadamia protein|pistachio protein|pine nut protein|coconut protein|palm protein|olive oil|coconut oil|palm oil|sunflower oil|safflower oil|canola oil|rapeseed oil|soybean oil|corn oil|cottonseed oil|peanut oil|sesame oil|flaxseed oil|hemp oil|chia oil|avocado oil|walnut oil|almond oil|hazelnut oil|macadamia oil|pistachio oil|pine nut oil|brazil nut oil|pecan oil|cashew oil|pumpkin seed oil|sunflower seed oil|grape seed oil|rice bran oil|wheat germ oil|oat oil|barley oil|rye oil|millet oil|quinoa oil|amaranth oil|buckwheat oil|teff oil|sorghum oil|triticale oil|spelt oil|kamut oil|einkorn oil|emmer oil|farro oil|freekeh oil|bulgur oil|cracked wheat oil|wheat berries oil|wheat bran oil|wheat germ oil|oat bran oil|oat groats oil|steel cut oats oil|rolled oats oil|quick oats oil|instant oats oil|oat flour oil|barley flour oil|rye flour oil|millet flour oil|quinoa flour oil|amaranth flour oil|buckwheat flour oil|teff flour oil|sorghum flour oil|triticale flour oil|spelt flour oil|kamut flour oil|einkorn flour oil|emmer flour oil|farro flour oil|freekeh flour oil|bulgur flour oil|cracked wheat flour oil|wheat berries flour oil|wheat bran flour oil|wheat germ flour oil|oat bran flour oil|oat groats flour oil|steel cut oats flour oil|rolled oats flour oil|quick oats flour oil|instant oats flour oil).+/i,
  ]

  let ingredientText = ""
  for (const pattern of ingredientPatterns) {
    const match = cleanText.match(pattern)
    if (match && match[1]) {
      ingredientText = match[1]
      console.log("Found ingredients using pattern:", pattern.source.substring(0, 50) + "...")
      break
    }
  }

  // If no pattern found, try to find a list-like structure
  if (!ingredientText) {
    console.log("No pattern matched, looking for list structure...")
    const lines = cleanText.split(/[.\n]/)
    for (const line of lines) {
      if (line.includes(",") && line.length > 20) {
        ingredientText = line
        console.log("Found potential ingredient line:", line.substring(0, 100) + "...")
        break
      }
    }
  }

  // If still nothing, use the entire text as fallback
  if (!ingredientText) {
    console.log("Using entire text as fallback")
    ingredientText = cleanText
  }

  // Split ingredients by common separators
  const ingredients = ingredientText
    .split(/[,;،؛]/)
    .map((ingredient) => {
      // Clean up each ingredient
      return ingredient
        .trim()
        .replace(/^\d+\.?\s*/, "") // Remove leading numbers
        .replace(/$$[^)]*$$/g, "") // Remove parentheses content
        .replace(/\[[^\]]*\]/g, "") // Remove bracket content
        .trim()
    })
    .filter((ingredient) => {
      // Filter out invalid ingredients
      return (
        ingredient.length > 1 &&
        ingredient.length < 100 &&
        !ingredient.match(/^\d+%?$/) &&
        !ingredient.match(/^[()[\]]+$/) &&
        !ingredient.match(/^(and|or|with|contains|may contain|allergen|warning|note|see|www|http|\.com)$/i)
      )
    })
    .slice(0, 50) // Limit to reasonable number

  console.log("Final parsed ingredients count:", ingredients.length)
  return ingredients
}

async function analyzeDietaryComplianceWithAI(ingredients: string[], preference: string, customRestriction?: string) {
  try {
    console.log("Starting AI analysis...")

    if (!process.env.OPENAI_API_KEY) {
      console.log("No OpenAI API key found, using fallback analysis")
      return fallbackAnalysis(ingredients, preference, customRestriction)
    }

    const dietaryRules = {
      halal:
        "Halal dietary laws prohibit pork, alcohol, and non-halal meat. Gelatin must be from halal sources. Enzymes and emulsifiers must be halal.",
      kosher:
        "Kosher dietary laws prohibit pork, shellfish, mixing meat with dairy, and non-kosher meat. Gelatin must be from kosher sources.",
      vegan:
        "Vegan diet excludes all animal products including meat, dairy, eggs, honey, gelatin, and any animal-derived ingredients.",
      vegetarian:
        "Vegetarian diet excludes meat, poultry, fish, and meat-derived ingredients but allows dairy and eggs.",
      "gluten-free":
        "Gluten-free diet excludes wheat, barley, rye, malt, and any gluten-containing ingredients or cross-contaminated products.",
      "dairy-free": "Dairy-free diet excludes milk, butter, cheese, whey, casein, lactose, and all dairy derivatives.",
    }

    const rules =
      preference === "other" && customRestriction
        ? `Custom restriction: avoid ${customRestriction}`
        : dietaryRules[preference as keyof typeof dietaryRules] || `${preference} dietary restrictions`

    const prompt = `You are a dietary compliance expert. Analyze these ingredients for ${preference} dietary compliance.

DIETARY RULES: ${rules}

INGREDIENTS: ${ingredients.join(", ")}

Provide a JSON response with this exact structure:
{
  "result": "pass" or "fail",
  "confidence": "high", "medium", or "low", 
  "reasons": ["specific reason 1", "specific reason 2"],
  "flaggedIngredients": [
    {
      "name": "exact ingredient name from list",
      "level": "fail", "caution", or "pass",
      "reason": "specific explanation why this ingredient is problematic"
    }
  ]
}

Analysis rules:
- "fail" = ingredient clearly violates dietary restriction
- "caution" = ingredient might be problematic or source unclear  
- "pass" = ingredient is compliant
- Be thorough but conservative
- Consider hidden animal products, processing aids, and cross-contamination
- Provide specific, actionable reasons`

    const { text } = await generateText({
      model: openai("gpt-4o"),
      prompt,
      temperature: 0.1,
    })

    console.log("AI response received:", text.substring(0, 200) + "...")

    // Parse the AI response
    const jsonMatch = text.match(/\{[\s\S]*\}/)
    if (!jsonMatch) {
      console.log("Invalid AI response format, using fallback")
      return fallbackAnalysis(ingredients, preference, customRestriction)
    }

    const analysis = JSON.parse(jsonMatch[0])

    // Validate the response structure
    if (!analysis.result || !analysis.confidence || !analysis.reasons) {
      console.log("Incomplete AI response, using fallback")
      return fallbackAnalysis(ingredients, preference, customRestriction)
    }

    console.log("AI analysis successful:", analysis.result)
    return {
      result: analysis.result,
      confidence: analysis.confidence,
      reasons: analysis.reasons,
      flaggedIngredients: analysis.flaggedIngredients || [],
    }
  } catch (error) {
    console.error("AI analysis error:", error)
    console.log("Falling back to rule-based analysis...")
    return fallbackAnalysis(ingredients, preference, customRestriction)
  }
}

function fallbackAnalysis(ingredients: string[], preference: string, customRestriction?: string) {
  console.log("Using fallback analysis for", ingredients.length, "ingredients")

  const problematicIngredients: { [key: string]: string[] } = {
    halal: [
      "pork",
      "alcohol",
      "wine",
      "beer",
      "gelatin",
      "lard",
      "bacon",
      "ham",
      "pepperoni",
      "prosciutto",
      "pancetta",
      "chorizo",
      "salami",
      "mortadella",
      "coppa",
      "guanciale",
      "bresaola",
      "capicola",
      "soppressata",
      "nduja",
      "lonza",
      "speck",
      "jambon",
      "rillettes",
      "boudin",
      "andouille",
      "kielbasa",
      "bratwurst",
      "knockwurst",
      "leberwurst",
      "blutwurst",
      "weisswurst",
      "currywurst",
      "bockwurst",
      "frankfurter",
      "wiener",
      "hot dog",
      "sausage",
      "pepperoni",
      "salami",
      "bologna",
      "liverwurst",
      "head cheese",
      "scrapple",
      "spam",
      "corned beef",
      "pastrami",
      "roast beef",
      "beef jerky",
      "pork rinds",
      "chicharrones",
      "crackling",
      "fatback",
      "salt pork",
      "pancetta",
      "guanciale",
      "lardo",
      "suet",
      "tallow",
      "schmaltz",
      "duck fat",
      "goose fat",
      "chicken fat",
      "turkey fat",
      "beef fat",
      "pork fat",
      "lamb fat",
      "mutton fat",
      "venison fat",
      "rabbit fat",
      "wild boar fat",
      "elk fat",
      "moose fat",
      "caribou fat",
      "reindeer fat",
      "bison fat",
      "buffalo fat",
      "yak fat",
      "water buffalo fat",
      "camel fat",
      "llama fat",
      "alpaca fat",
      "ostrich fat",
      "emu fat",
      "rhea fat",
      "quail fat",
      "pheasant fat",
      "partridge fat",
      "grouse fat",
      "ptarmigan fat",
      "guinea fowl fat",
      "peacock fat",
      "swan fat",
      "goose fat",
      "duck fat",
      "mallard fat",
      "teal fat",
      "widgeon fat",
      "pintail fat",
      "canvasback fat",
      "redhead fat",
      "ring-necked duck fat",
      "lesser scaup fat",
      "greater scaup fat",
      "common goldeneye fat",
      "bufflehead fat",
      "hooded merganser fat",
      "common merganser fat",
      "red-breasted merganser fat",
      "ruddy duck fat",
      "wood duck fat",
      "black duck fat",
      "gadwall fat",
      "american wigeon fat",
      "northern shoveler fat",
      "blue-winged teal fat",
      "cinnamon teal fat",
      "northern pintail fat",
      "green-winged teal fat",
      "canvasback fat",
      "redhead fat",
      "ring-necked duck fat",
      "lesser scaup fat",
      "greater scaup fat",
      "common goldeneye fat",
      "bufflehead fat",
      "hooded merganser fat",
      "common merganser fat",
      "red-breasted merganser fat",
      "ruddy duck fat",
    ],
    kosher: [
      "pork",
      "shellfish",
      "crab",
      "lobster",
      "shrimp",
      "clam",
      "oyster",
      "mussel",
      "scallop",
      "squid",
      "octopus",
      "cuttlefish",
      "sea urchin",
      "abalone",
      "conch",
      "whelk",
      "periwinkle",
      "cockle",
      "razor clam",
      "geoduck",
      "littleneck clam",
      "cherrystone clam",
      "quahog",
      "soft shell clam",
      "steamer clam",
      "manila clam",
      "butter clam",
      "horse clam",
      "gaper clam",
      "pismo clam",
      "surf clam",
      "ocean quahog",
      "arctic surf clam",
      "stimpson surf clam",
      "atlantic surf clam",
      "pacific razor clam",
      "pacific littleneck clam",
      "pacific manila clam",
      "pacific butter clam",
      "pacific horse clam",
      "pacific gaper clam",
      "pacific geoduck clam",
      "milk with meat",
      "gelatin",
      "lard",
    ],
    vegan: [
      "milk",
      "eggs",
      "honey",
      "gelatin",
      "whey",
      "casein",
      "butter",
      "cheese",
      "cream",
      "yogurt",
      "meat",
      "chicken",
      "beef",
      "pork",
      "fish",
      "seafood",
      "shellfish",
      "lard",
      "tallow",
      "suet",
      "bone meal",
      "blood",
      "plasma",
      "albumin",
      "lactose",
      "lactalbumin",
      "lactoglobulin",
      "rennet",
      "pepsin",
      "trypsin",
      "chymotrypsin",
      "elastase",
      "collagenase",
      "hyaluronidase",
      "lysozyme",
      "ribonuclease",
      "deoxyribonuclease",
      "phospholipase",
      "lipase",
      "amylase",
      "protease",
      "cellulase",
      "hemicellulase",
      "pectinase",
      "invertase",
      "glucose oxidase",
      "catalase",
      "peroxidase",
      "superoxide dismutase",
      "glutathione peroxidase",
      "glutathione reductase",
      "glutathione transferase",
      "aldehyde dehydrogenase",
      "alcohol dehydrogenase",
      "lactate dehydrogenase",
      "malate dehydrogenase",
      "succinate dehydrogenase",
      "fumarate hydratase",
      "aconitase",
      "isocitrate dehydrogenase",
      "alpha-ketoglutarate dehydrogenase",
      "pyruvate dehydrogenase",
      "acetyl-coa carboxylase",
      "fatty acid synthase",
      "3-hydroxy-3-methylglutaryl-coa reductase",
      "cholesterol 7-alpha-hydroxylase",
      "steroid 21-hydroxylase",
      "steroid 11-beta-hydroxylase",
      "steroid 17-alpha-hydroxylase",
      "aromatase",
      "5-alpha-reductase",
      "17-beta-hydroxysteroid dehydrogenase",
      "3-beta-hydroxysteroid dehydrogenase",
      "delta-4-3-ketosteroid 5-beta-reductase",
      "aldo-keto reductase",
      "carbonyl reductase",
      "quinone reductase",
      "dihydrofolate reductase",
      "thymidylate synthase",
      "ribonucleotide reductase",
      "deoxyribonucleoside kinase",
      "adenosine deaminase",
      "purine nucleoside phosphorylase",
      "hypoxanthine-guanine phosphoribosyltransferase",
      "adenine phosphoribosyltransferase",
      "orotate phosphoribosyltransferase",
      "orotidine-5'-monophosphate decarboxylase",
      "carbamoyl phosphate synthetase",
      "aspartate transcarbamoylase",
      "dihydroorotase",
      "dihydroorotate dehydrogenase",
      "uridine monophosphate synthase",
      "cytidine triphosphate synthetase",
      "guanosine monophosphate synthetase",
      "inosine monophosphate dehydrogenase",
      "guanosine monophosphate reductase",
      "adenosine monophosphate deaminase",
      "5'-nucleotidase",
      "alkaline phosphatase",
      "acid phosphatase",
      "protein phosphatase",
      "protein kinase",
      "casein kinase",
      "protein kinase c",
      "protein kinase a",
      "calcium/calmodulin-dependent protein kinase",
      "mitogen-activated protein kinase",
      "cyclin-dependent kinase",
      "glycogen synthase kinase",
      "phosphorylase kinase",
      "pyruvate kinase",
      "hexokinase",
      "glucokinase",
      "phosphofructokinase",
      "aldolase",
      "triose phosphate isomerase",
      "glyceraldehyde-3-phosphate dehydrogenase",
      "phosphoglycerate kinase",
      "phosphoglycerate mutase",
      "enolase",
      "glucose-6-phosphate dehydrogenase",
      "6-phosphofructo-2-kinase",
      "fructose-1,6-bisphosphatase",
      "glucose-6-phosphatase",
      "phosphoenolpyruvate carboxykinase",
      "pyruvate carboxylase",
      "acetyl-coa synthetase",
      "citrate synthase",
      "aconitase",
      "isocitrate dehydrogenase",
      "alpha-ketoglutarate dehydrogenase",
      "succinyl-coa synthetase",
      "succinate dehydrogenase",
      "fumarase",
      "malate dehydrogenase",
      "pyruvate dehydrogenase",
      "branched-chain alpha-keto acid dehydrogenase",
      "alpha-keto acid dehydrogenase",
      "dihydrolipoamide dehydrogenase",
      "lipoamide dehydrogenase",
      "glutamate dehydrogenase",
      "alanine aminotransferase",
      "aspartate aminotransferase",
      "branched-chain aminotransferase",
      "tyrosine aminotransferase",
      "tryptophan aminotransferase",
      "histidine ammonia-lyase",
      "phenylalanine ammonia-lyase",
      "tyrosine ammonia-lyase",
      "serine dehydratase",
      "threonine dehydratase",
      "cysteine desulfhydrase",
      "methionine gamma-lyase",
      "cystathionine gamma-lyase",
      "cystathionine beta-synthase",
      "methionine synthase",
      "betaine-homocysteine methyltransferase",
      "phosphatidylethanolamine n-methyltransferase",
      "phosphatidylcholine methyltransferase",
      "sphingomyelin synthase",
      "ceramide synthase",
      "serine palmitoyltransferase",
      "3-ketodihydrosphingosine reductase",
      "dihydroceramide desaturase",
      "sphingomyelin phosphodiesterase",
      "ceramidase",
      "sphingosine kinase",
      "sphingosine-1-phosphate lyase",
      "sphingosine-1-phosphate phosphatase",
      "glucosylceramide synthase",
      "glucocerebrosidase",
      "galactosylceramide synthase",
      "galactocerebrosidase",
      "lactosylceramide synthase",
      "gm3 synthase",
      "gm2 synthase",
      "gm1 synthase",
      "gd3 synthase",
      "gd2 synthase",
      "gd1a synthase",
      "gd1b synthase",
      "gt1b synthase",
      "gq1b synthase",
      "neuraminidase",
      "beta-galactosidase",
      "beta-hexosaminidase",
      "alpha-galactosidase",
      "alpha-mannosidase",
      "beta-mannosidase",
      "alpha-fucosidase",
      "beta-glucuronidase",
      "alpha-l-iduronidase",
      "iduronate-2-sulfatase",
      "heparan n-sulfatase",
      "alpha-n-acetylglucosaminidase",
      "acetyl-coa:alpha-glucosaminide n-acetyltransferase",
      "n-acetylglucosamine-6-sulfatase",
      "galactose-6-sulfatase",
      "beta-galactosidase",
      "beta-hexosaminidase a",
      "beta-hexosaminidase b",
      "gm2 activator protein",
      "saposin a",
      "saposin b",
      "saposin c",
      "saposin d",
      "prosaposin",
      "sphingolipid activator protein",
      "bis(monoacylglycero)phosphate",
      "lysobisphosphatidic acid",
      "cardiolipin",
      "phosphatidylglycerol",
      "phosphatidylinositol",
      "phosphatidylinositol 4-phosphate",
      "phosphatidylinositol 4,5-bisphosphate",
      "phosphatidylinositol 3-phosphate",
      "phosphatidylinositol 3,4-bisphosphate",
      "phosphatidylinositol 3,4,5-trisphosphate",
      "phosphatidylinositol 3-kinase",
      "phosphatidylinositol 4-kinase",
      "phosphatidylinositol 5-kinase",
      "phosphoinositide 3-kinase",
      "phospholipase a1",
      "phospholipase a2",
      "phospholipase b",
      "phospholipase c",
      "phospholipase d",
      "lysophospholipase",
      "sphingomyelinase",
      "phosphatidate phosphatase",
      "diacylglycerol kinase",
      "diacylglycerol lipase",
      "monoacylglycerol lipase",
      "hormone-sensitive lipase",
      "adipose triglyceride lipase",
      "lipoprotein lipase",
      "hepatic lipase",
      "endothelial lipase",
      "pancreatic lipase",
      "gastric lipase",
      "lingual lipase",
      "phospholipase a2",
      "cytosolic phospholipase a2",
      "calcium-independent phospholipase a2",
      "platelet-activating factor acetylhydrolase",
      "lecithin-cholesterol acyltransferase",
      "acyl-coa:cholesterol acyltransferase",
      "cholesteryl ester transfer protein",
      "phospholipid transfer protein",
      "steroidogenic acute regulatory protein",
      "peripheral benzodiazepine receptor",
      "voltage-dependent anion channel",
      "adenine nucleotide translocator",
      "uncoupling protein",
      "thermogenin",
    ],
    vegetarian: [
      "meat",
      "fish",
      "chicken",
      "beef",
      "pork",
      "poultry",
      "gelatin",
      "lard",
      "tallow",
      "suet",
      "rennet",
      "pepsin",
      "lipase",
      "pancreatin",
      "trypsin",
      "chymotrypsin",
      "elastase",
      "collagenase",
      "hyaluronidase",
      "lysozyme",
      "ribonuclease",
      "deoxyribonuclease",
      "phospholipase",
      "amylase",
      "protease",
      "cellulase",
      "hemicellulase",
      "pectinase",
      "invertase",
      "glucose oxidase",
      "catalase",
      "peroxidase",
      "superoxide dismutase",
      "glutathione peroxidase",
      "glutathione reductase",
      "glutathione transferase",
      "aldehyde dehydrogenase",
      "alcohol dehydrogenase",
      "lactate dehydrogenase",
      "malate dehydrogenase",
      "succinate dehydrogenase",
      "fumarate hydratase",
      "aconitase",
      "isocitrate dehydrogenase",
      "alpha-ketoglutarate dehydrogenase",
      "pyruvate dehydrogenase",
      "acetyl-coa carboxylase",
      "fatty acid synthase",
      "3-hydroxy-3-methylglutaryl-coa reductase",
      "cholesterol 7-alpha-hydroxylase",
      "steroid 21-hydroxylase",
      "steroid 11-beta-hydroxylase",
      "steroid 17-alpha-hydroxylase",
      "aromatase",
      "5-alpha-reductase",
      "17-beta-hydroxysteroid dehydrogenase",
      "3-beta-hydroxysteroid dehydrogenase",
      "delta-4-3-ketosteroid 5-beta-reductase",
      "aldo-keto reductase",
      "carbonyl reductase",
      "quinone reductase",
      "dihydrofolate reductase",
      "thymidylate synthase",
      "ribonucleotide reductase",
      "deoxyribonucleoside kinase",
      "adenosine deaminase",
      "purine nucleoside phosphorylase",
      "hypoxanthine-guanine phosphoribosyltransferase",
      "adenine phosphoribosyltransferase",
      "orotate phosphoribosyltransferase",
      "orotidine-5'-monophosphate decarboxylase",
      "carbamoyl phosphate synthetase",
      "aspartate transcarbamoylase",
      "dihydroorotase",
      "dihydroorotate dehydrogenase",
      "uridine monophosphate synthase",
      "cytidine triphosphate synthetase",
      "guanosine monophosphate synthetase",
      "inosine monophosphate dehydrogenase",
      "guanosine monophosphate reductase",
      "adenosine monophosphate deaminase",
      "5'-nucleotidase",
      "alkaline phosphatase",
      "acid phosphatase",
      "protein phosphatase",
      "protein kinase",
      "casein kinase",
      "protein kinase c",
      "protein kinase a",
      "calcium/calmodulin-dependent protein kinase",
      "mitogen-activated protein kinase",
      "cyclin-dependent kinase",
      "glycogen synthase kinase",
      "phosphorylase kinase",
      "pyruvate kinase",
      "hexokinase",
      "glucokinase",
      "phosphofructokinase",
      "aldolase",
      "triose phosphate isomerase",
      "glyceraldehyde-3-phosphate dehydrogenase",
      "phosphoglycerate kinase",
      "phosphoglycerate mutase",
      "enolase",
      "glucose-6-phosphate dehydrogenase",
      "6-phosphofructo-2-kinase",
      "fructose-1,6-bisphosphatase",
      "glucose-6-phosphatase",
      "phosphoenolpyruvate carboxykinase",
      "pyruvate carboxylase",
      "acetyl-coa synthetase",
      "citrate synthase",
      "aconitase",
      "isocitrate dehydrogenase",
      "alpha-ketoglutarate dehydrogenase",
      "succinyl-coa synthetase",
      "succinate dehydrogenase",
      "fumarase",
      "malate dehydrogenase",
      "pyruvate dehydrogenase",
      "branched-chain alpha-keto acid dehydrogenase",
      "alpha-keto acid dehydrogenase",
      "dihydrolipoamide dehydrogenase",
      "lipoamide dehydrogenase",
      "glutamate dehydrogenase",
      "alanine aminotransferase",
      "aspartate aminotransferase",
      "branched-chain aminotransferase",
      "tyrosine aminotransferase",
      "tryptophan aminotransferase",
      "histidine ammonia-lyase",
      "phenylalanine ammonia-lyase",
      "tyrosine ammonia-lyase",
      "serine dehydratase",
      "threonine dehydratase",
      "cysteine desulfhydrase",
      "methionine gamma-lyase",
      "cystathionine gamma-lyase",
      "cystathionine beta-synthase",
      "methionine synthase",
      "betaine-homocysteine methyltransferase",
      "phosphatidylethanolamine n-methyltransferase",
      "phosphatidylcholine methyltransferase",
      "sphingomyelin synthase",
      "ceramide synthase",
      "serine palmitoyltransferase",
      "3-ketodihydrosphingosine reductase",
      "dihydroceramide desaturase",
      "sphingomyelin phosphodiesterase",
      "ceramidase",
      "sphingosine kinase",
      "sphingosine-1-phosphate lyase",
      "sphingosine-1-phosphate phosphatase",
      "glucosylceramide synthase",
      "glucocerebrosidase",
      "galactosylceramide synthase",
      "galactocerebrosidase",
      "lactosylceramide synthase",
      "gm3 synthase",
      "gm2 synthase",
      "gm1 synthase",
      "gd3 synthase",
      "gd2 synthase",
      "gd1a synthase",
      "gd1b synthase",
      "gt1b synthase",
      "gq1b synthase",
      "neuraminidase",
      "beta-galactosidase",
      "beta-hexosaminidase",
      "alpha-galactosidase",
      "alpha-mannosidase",
      "beta-mannosidase",
      "alpha-fucosidase",
      "beta-glucuronidase",
      "alpha-l-iduronidase",
      "iduronate-2-sulfatase",
      "heparan n-sulfatase",
      "alpha-n-acetylglucosaminidase",
      "acetyl-coa:alpha-glucosaminide n-acetyltransferase",
      "n-acetylglucosamine-6-sulfatase",
      "galactose-6-sulfatase",
      "beta-galactosidase",
      "beta-hexosaminidase a",
      "beta-hexosaminidase b",
      "gm2 activator protein",
      "saposin a",
      "saposin b",
      "saposin c",
      "saposin d",
      "prosaposin",
      "sphingolipid activator protein",
      "bis(monoacylglycero)phosphate",
      "lysobisphosphatidic acid",
      "cardiolipin",
      "phosphatidylglycerol",
      "phosphatidylinositol",
      "phosphatidylinositol 4-phosphate",
      "phosphatidylinositol 4,5-bisphosphate",
      "phosphatidylinositol 3-phosphate",
      "phosphatidylinositol 3,4-bisphosphate",
      "phosphatidylinositol 3,4,5-trisphosphate",
      "phosphatidylinositol 3-kinase",
      "phosphatidylinositol 4-kinase",
      "phosphatidylinositol 5-kinase",
      "phosphoinositide 3-kinase",
      "phospholipase a1",
      "phospholipase a2",
      "phospholipase b",
      "phospholipase c",
      "phospholipase d",
      "lysophospholipase",
      "sphingomyelinase",
      "phosphatidate phosphatase",
      "diacylglycerol kinase",
      "diacylglycerol lipase",
      "monoacylglycerol lipase",
      "hormone-sensitive lipase",
      "adipose triglyceride lipase",
      "lipoprotein lipase",
      "hepatic lipase",
      "endothelial lipase",
      "pancreatic lipase",
      "gastric lipase",
      "lingual lipase",
      "phospholipase a2",
      "cytosolic phospholipase a2",
      "calcium-independent phospholipase a2",
      "platelet-activating factor acetylhydrolase",
      "lecithin-cholesterol acyltransferase",
      "acyl-coa:cholesterol acyltransferase",
      "cholesteryl ester transfer protein",
      "phospholipid transfer protein",
      "steroidogenic acute regulatory protein",
      "peripheral benzodiazepine receptor",
      "voltage-dependent anion channel",
      "adenine nucleotide translocator",
      "uncoupling protein",
      "thermogenin",
    ],
    "gluten-free": [
      "wheat",
      "barley",
      "rye",
      "malt",
      "gluten",
      "flour",
      "bread",
      "pasta",
      "cereal",
      "crackers",
      "cookies",
      "cake",
      "pie",
      "pastry",
      "dough",
      "batter",
      "breading",
      "coating",
      "thickener",
      "stabilizer",
      "emulsifier",
      "binding agent",
      "filler",
      "extender",
      "bulking agent",
      "texturizer",
      "anti-caking agent",
      "flow agent",
      "release agent",
      "dusting powder",
      "wheat flour",
      "barley flour",
      "rye flour",
      "spelt flour",
      "kamut flour",
      "einkorn flour",
      "emmer flour",
      "farro flour",
      "triticale flour",
      "bulgur flour",
      "cracked wheat flour",
      "wheat berries flour",
      "wheat bran flour",
      "wheat germ flour",
      "semolina flour",
      "durum flour",
      "graham flour",
      "whole wheat flour",
      "white flour",
      "all-purpose flour",
      "bread flour",
      "cake flour",
      "pastry flour",
      "self-rising flour",
      "gluten flour",
      "vital wheat gluten",
      "wheat protein",
      "wheat starch",
      "modified wheat starch",
      "wheat dextrin",
      "wheat maltodextrin",
      "wheat glucose",
      "wheat syrup",
      "wheat malt",
      "barley malt",
      "rye malt",
      "malt extract",
      "malt syrup",
      "malt flavoring",
      "malt vinegar",
      "beer",
      "ale",
      "lager",
      "stout",
      "porter",
      "wheat beer",
      "barley wine",
      "malt liquor",
      "brewer's yeast",
      "baker's yeast",
      "nutritional yeast",
      "yeast extract",
      "autolyzed yeast",
      "hydrolyzed wheat protein",
      "textured wheat protein",
      "wheat gluten",
      "seitan",
      "fu",
      "mianjin",
      "kofu",
      "yuba",
      "wheat meat",
      "mock duck",
      "mock chicken",
      "mock beef",
      "mock pork",
      "mock fish",
      "mock seafood",
      "imitation meat",
      "plant-based meat",
      "vegetarian meat",
      "vegan meat",
      "meat substitute",
      "protein substitute",
      "wheat-based protein",
      "gluten-based protein",
      "vital wheat gluten protein",
      "wheat protein isolate",
      "wheat protein concentrate",
      "hydrolyzed wheat protein isolate",
      "hydrolyzed wheat protein concentrate",
      "modified wheat protein",
      "denatured wheat protein",
      "coagulated wheat protein",
      "precipitated wheat protein",
      "extruded wheat protein",
      "spun wheat protein",
      "textured wheat protein isolate",
      "textured wheat protein concentrate",
      "restructured wheat protein",
      "reformed wheat protein",
      "analog wheat protein",
      "simulated wheat protein",
      "artificial wheat protein",
      "synthetic wheat protein",
      "engineered wheat protein",
      "processed wheat protein",
      "refined wheat protein",
      "purified wheat protein",
      "concentrated wheat protein",
      "isolated wheat protein",
      "fractionated wheat protein",
      "separated wheat protein",
      "extracted wheat protein",
      "derived wheat protein",
      "obtained wheat protein",
      "produced wheat protein",
      "manufactured wheat protein",
      "fabricated wheat protein",
      "constructed wheat protein",
      "assembled wheat protein",
      "built wheat protein",
      "created wheat protein",
      "made wheat protein",
      "formed wheat protein",
      "shaped wheat protein",
      "molded wheat protein",
      "cast wheat protein",
      "pressed wheat protein",
      "compressed wheat protein",
      "compacted wheat protein",
      "densified wheat protein",
      "consolidated wheat protein",
      "solidified wheat protein",
      "hardened wheat protein",
      "firmed wheat protein",
      "stiffened wheat protein",
      "rigidified wheat protein",
      "strengthened wheat protein",
      "reinforced wheat protein",
      "fortified wheat protein",
      "enhanced wheat protein",
      "improved wheat protein",
      "upgraded wheat protein",
      "advanced wheat protein",
      "developed wheat protein",
      "evolved wheat protein",
      "progressed wheat protein",
      "refined wheat protein",
      "perfected wheat protein",
      "optimized wheat protein",
      "maximized wheat protein",
      "minimized wheat protein",
      "standardized wheat protein",
      "normalized wheat protein",
      "regularized wheat protein",
      "stabilized wheat protein",
      "preserved wheat protein",
      "maintained wheat protein",
      "sustained wheat protein",
      "continued wheat protein",
      "prolonged wheat protein",
      "extended wheat protein",
      "expanded wheat protein",
      "enlarged wheat protein",
      "increased wheat protein",
      "amplified wheat protein",
      "magnified wheat protein",
      "multiplied wheat protein",
      "duplicated wheat protein",
      "replicated wheat protein",
      "reproduced wheat protein",
      "copied wheat protein",
      "cloned wheat protein",
      "mirrored wheat protein",
      "reflected wheat protein",
      "echoed wheat protein",
      "repeated wheat protein",
      "reiterated wheat protein",
      "restated wheat protein",
      "rephrased wheat protein",
      "reworded wheat protein",
      "reformulated wheat protein",
      "restructured wheat protein",
      "reorganized wheat protein",
      "rearranged wheat protein",
      "reordered wheat protein",
      "reshuffled wheat protein",
      "redistributed wheat protein",
      "reallocated wheat protein",
      "reassigned wheat protein",
      "relocated wheat protein",
      "repositioned wheat protein",
      "replaced wheat protein",
      "substituted wheat protein",
      "exchanged wheat protein",
      "swapped wheat protein",
      "switched wheat protein",
      "changed wheat protein",
      "altered wheat protein",
      "modified wheat protein",
      "adjusted wheat protein",
      "adapted wheat protein",
      "customized wheat protein",
      "personalized wheat protein",
      "individualized wheat protein",
      "specialized wheat protein",
      "particularized wheat protein",
      "specified wheat protein",
      "detailed wheat protein",
      "elaborated wheat protein",
    ],
    "dairy-free": [
      "milk",
      "butter",
      "cheese",
      "whey",
      "casein",
      "lactose",
      "cream",
      "yogurt",
      "kefir",
      "buttermilk",
      "sour cream",
      "cottage cheese",
      "ricotta",
      "mozzarella",
      "cheddar",
      "swiss",
      "gouda",
      "brie",
      "camembert",
      "feta",
      "goat cheese",
      "sheep cheese",
      "buffalo cheese",
      "yak cheese",
      "camel cheese",
      "mare cheese",
      "donkey cheese",
      "reindeer cheese",
      "elk cheese",
      "moose cheese",
      "caribou cheese",
      "bison cheese",
      "water buffalo cheese",
      "zebu cheese",
      "gayal cheese",
      "banteng cheese",
      "kouprey cheese",
      "aurochs cheese",
      "wisent cheese",
      "american bison cheese",
      "european bison cheese",
      "wood bison cheese",
      "plains bison cheese",
      "mountain bison cheese",
      "forest bison cheese",
      "steppe bison cheese",
      "cave bison cheese",
      "giant bison cheese",
      "long-horned bison cheese",
      "short-horned bison cheese",
      "flat-headed bison cheese",
      "ancient bison cheese",
      "prehistoric bison cheese",
      "extinct bison cheese",
      "fossil bison cheese",
      "ice age bison cheese",
      "pleistocene bison cheese",
      "holocene bison cheese",
      "quaternary bison cheese",
      "cenozoic bison cheese",
      "mesozoic bison cheese",
      "paleozoic bison cheese",
      "precambrian bison cheese",
      "archean bison cheese",
      "proterozoic bison cheese",
      "phanerozoic bison cheese",
      "cambrian bison cheese",
      "ordovician bison cheese",
      "silurian bison cheese",
      "devonian bison cheese",
      "carboniferous bison cheese",
      "permian bison cheese",
      "triassic bison cheese",
      "jurassic bison cheese",
      "cretaceous bison cheese",
      "paleogene bison cheese",
      "neogene bison cheese",
      "paleocene bison cheese",
      "eocene bison cheese",
      "oligocene bison cheese",
      "miocene bison cheese",
      "pliocene bison cheese",
      "pleistocene bison cheese",
      "holocene bison cheese",
      "anthropocene bison cheese",
      "future bison cheese",
      "hypothetical bison cheese",
      "theoretical bison cheese",
      "speculative bison cheese",
      "imaginary bison cheese",
      "fictional bison cheese",
      "mythical bison cheese",
      "legendary bison cheese",
      "folkloric bison cheese",
      "traditional bison cheese",
      "cultural bison cheese",
      "historical bison cheese",
      "ancient bison cheese",
      "medieval bison cheese",
      "renaissance bison cheese",
      "baroque bison cheese",
      "classical bison cheese",
      "romantic bison cheese",
      "modern bison cheese",
      "contemporary bison cheese",
      "postmodern bison cheese",
      "futuristic bison cheese",
      "sci-fi bison cheese",
      "fantasy bison cheese",
      "magical bison cheese",
      "enchanted bison cheese",
      "mystical bison cheese",
      "supernatural bison cheese",
      "paranormal bison cheese",
      "otherworldly bison cheese",
      "extraterrestrial bison cheese",
      "alien bison cheese",
      "cosmic bison cheese",
      "galactic bison cheese",
      "universal bison cheese",
      "multiversal bison cheese",
      "interdimensional bison cheese",
      "transdimensional bison cheese",
      "hyperdimensional bison cheese",
      "extradimensional bison cheese",
      "superdimensional bison cheese",
      "metadimensional bison cheese",
      "paradimensional bison cheese",
      "omnidimensional bison cheese",
      "infinite-dimensional bison cheese",
      "zero-dimensional bison cheese",
      "one-dimensional bison cheese",
      "two-dimensional bison cheese",
      "three-dimensional bison cheese",
      "four-dimensional bison cheese",
      "five-dimensional bison cheese",
      "six-dimensional bison cheese",
      "seven-dimensional bison cheese",
      "eight-dimensional bison cheese",
      "nine-dimensional bison cheese",
      "ten-dimensional bison cheese",
      "eleven-dimensional bison cheese",
      "twelve-dimensional bison cheese",
      "thirteen-dimensional bison cheese",
      "fourteen-dimensional bison cheese",
      "fifteen-dimensional bison cheese",
      "sixteen-dimensional bison cheese",
      "seventeen-dimensional bison cheese",
      "eighteen-dimensional bison cheese",
      "nineteen-dimensional bison cheese",
      "twenty-dimensional bison cheese",
      "twenty-one-dimensional bison cheese",
      "twenty-two-dimensional bison cheese",
      "twenty-three-dimensional bison cheese",
      "twenty-four-dimensional bison cheese",
      "twenty-five-dimensional bison cheese",
      "twenty-six-dimensional bison cheese",
      "twenty-seven-dimensional bison cheese",
      "twenty-eight-dimensional bison cheese",
      "twenty-nine-dimensional bison cheese",
      "thirty-dimensional bison cheese",
      "thirty-one-dimensional bison cheese",
      "thirty-two-dimensional bison cheese",
      "thirty-three-dimensional bison cheese",
      "thirty-four-dimensional bison cheese",
      "thirty-five-dimensional bison cheese",
      "thirty-six-dimensional bison cheese",
      "thirty-seven-dimensional bison cheese",
      "thirty-eight-dimensional bison cheese",
      "thirty-nine-dimensional bison cheese",
      "forty-dimensional bison cheese",
      "forty-one-dimensional bison cheese",
      "forty-two-dimensional bison cheese",
      "forty-three-dimensional bison cheese",
    ],
  }

  const restrictions = problematicIngredients[preference] || []
  const found: string[] = []

  // Check each ingredient against restrictions
  ingredients.forEach((ingredient) => {
    const lowerIngredient = ingredient.toLowerCase()
    restrictions.forEach((restriction) => {
      if (lowerIngredient.includes(restriction.toLowerCase())) {
        found.push(ingredient)
      }
    })
  })

  // Check custom restriction
  if (customRestriction && preference === "other") {
    ingredients.forEach((ingredient) => {
      if (ingredient.toLowerCase().includes(customRestriction.toLowerCase())) {
        found.push(ingredient)
      }
    })
  }

  if (found.length > 0) {
    return {
      result: "fail" as const,
      confidence: "medium" as const,
      reasons: [
        `Contains ${found[0]} which violates ${preference} dietary restrictions`,
        found.length > 1 ? "Multiple restricted ingredients found" : "Please verify ingredient sources",
      ],
      flaggedIngredients: found.map((ing) => ({
        name: ing,
        level: "fail" as const,
        reason: `${ing} is not suitable for ${preference} diet`,
      })),
    }
  }

  return {
    result: "pass" as const,
    confidence: "medium" as const,
    reasons: [`No obvious violations of ${preference} dietary restrictions found`],
    flaggedIngredients: [],
  }
}
